##
## Makefile for  in /home/lao_e/rendu/PSU_2014_philo/threads_exemple/ex1
## 
## Made by Aurélie LAO
## Login   <lao_e@epitech.net>
## 
## Started on  Sun Feb 22 09:49:35 2015 Aurélie LAO
## Last update Sun Feb 22 10:07:19 2015 Aurélie LAO
##

CC	=	gcc

RM	=	rm -f

SRC	=	ex2.c

NAME	=	test02_pthread

all	:	$(NAME)

$(NAME)	:
		$(CC) -o $(NAME) $(SRC) -lpthread

fclean	:
		$(RM) $(NAME)

re	:	fclean all

.PHONY	:	all fclean re
